version: '3'
services:
  node:
    image: tanyanovik/node
    build:
     context: .
     dockerfile: Dockerfile
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=4000
    volumes:
      - .:/usr/app
      - ./log:/usr/app/log
    networks:
      - app-network
  postgres:
    image: tanyanovik/postgres
    build: ./database
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:
  log: